version: '3'
services:
  db:
    # install postgres to write 
    # data into db
    image: postgres:12
    container_name: postgres
    volumes:
    -  $PWD/pg-data:/var/lib/postgresql/data
    ports: 
     - 54320:5432
    environment:   
         POSTGRES_PASSWORD: docker
         POSTGRES_USER: admin
         POSTGRES_DB: sitemap_db
         PGDATA: /var/lib/postgresql/data
    restart: always
  app:
    # download already built image with sitemap 
    # python script inside
    image: driver220v/sitemap:improved
    container_name: sitemap
    links:
     - db
    entrypoint: sleep 50000
